"""Data models for Incident Response Agent."""
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class IncidentSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class IncidentStatus(str, Enum):
    DETECTED = "DETECTED"
    INVESTIGATING = "INVESTIGATING"
    ROOT_CAUSE_IDENTIFIED = "ROOT_CAUSE_IDENTIFIED"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"
    MITIGATED = "MITIGATED"
    RESOLVED = "RESOLVED"


class ActionType(str, Enum):
    ROLLBACK_DEPLOYMENT = "ROLLBACK_DEPLOYMENT"
    RESTART_SERVICE = "RESTART_SERVICE"
    SCALE_UP = "SCALE_UP"
    THROTTLE_TRAFFIC = "THROTTLE_TRAFFIC"
    MANUAL_INVESTIGATION = "MANUAL_INVESTIGATION"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"


class RemediationAction(BaseModel):
    """Proposed remediation action requiring human confirmation."""
    action_id: str
    action_type: ActionType
    title: str
    description: str
    target_service: str
    target_version: Optional[str] = None
    rollback_from: Optional[str] = None
    command_preview: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    risk_level: str = "LOW"
    approval_status: ApprovalStatus = ApprovalStatus.PENDING
    reviewer: Optional[str] = None
    reviewed_at: Optional[str] = None
    execution_result: Optional[Dict[str, Any]] = None


class LogEvidence(BaseModel):
    total_errors: int
    first_error_time: Optional[str] = None
    primary_exception: Optional[str] = None
    stack_traces: List[str] = []
    error_sample: List[Dict[str, Any]] = []


class DeployEvidence(BaseModel):
    suspect_deployment: Optional[Dict[str, Any]] = None
    time_delta_seconds: Optional[float] = None
    commit_hash: Optional[str] = None
    author: Optional[str] = None
    changes: List[str] = []


class MetricEvidence(BaseModel):
    anomalies: List[Dict[str, Any]] = []
    error_rate_peak: Optional[float] = None
    latency_p99_peak: Optional[float] = None


class RootCauseAnalysis(BaseModel):
    summary: str
    probable_culprit: str
    confidence: float
    culprit_deployment_id: Optional[str] = None
    culprit_commit: Optional[str] = None
    exception_type: Optional[str] = None
    faulty_file_and_line: Optional[str] = None
    timeline_summary: List[str] = []


class DiagnosisReport(BaseModel):
    """Structured diagnosis report generated by the Claude diagnosis agent."""
    root_cause_hypothesis: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    supporting_evidence: List[str] = []
    recommended_action: Dict[str, Any] = {}
    risk_level: str = "LOW"
    reasoning_steps: List[str] = []
    alert_summary: Optional[str] = None
    affected_service: Optional[str] = None
    suspect_deploy_id: Optional[str] = None


class DecisionRecord(BaseModel):
    """Audit record for human action approval/rejection decisions."""
    decision_id: str
    incident_id: str
    service: str
    action_id: str
    action_title: str
    decision: str  # "APPROVED" or "REJECTED"
    reviewer: str
    timestamp: str
    command_preview: str
    execution_result: Optional[Dict[str, Any]] = None


class Incident(BaseModel):
    """Full incident record managed by the agent."""
    id: str
    title: str
    service: str
    severity: IncidentSeverity
    status: IncidentStatus
    detected_at: str
    updated_at: str
    description: Optional[str] = None
    log_evidence: Optional[LogEvidence] = None
    deploy_evidence: Optional[DeployEvidence] = None
    metric_evidence: Optional[MetricEvidence] = None
    root_cause: Optional[RootCauseAnalysis] = None
    actions: List[RemediationAction] = []
    diagnosis_report: Optional[DiagnosisReport] = None
    decision_history: List[DecisionRecord] = []
    auto_mitigate_deadline: Optional[str] = None
    auto_mitigated: bool = False
    policy_evaluation: Optional[Dict[str, Any]] = None


